## Data gathering
input:
  base_path: "../dados_titanic/raw"
  file_name: "train.csv"

output:
  base_path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Classification/titanic/dados_titanic/processed'
  file_name: "train.parquet"

save_plots:
  base_path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Classification/titanic/plots'

## Feature selection
input_feat_selection:
  base_path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Classification/titanic/dados_titanic/processed'
  file_name: "train.parquet"

save_reports:
  base_path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Classification/titanic/dados_titanic/reports'

feat_selection:
  base_path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Classification/titanic/dados_titanic/processed'
  X_train_file_name: "feat_X_train.parquet"
  X_test_file_name: "feat_X_test.parquet"
  y_train_file_name: "feat_y_train.parquet"
  y_test_file_name: "feat_y_test.parquet"

feat_selection_params:
  random_state: 23
  teste_size: 0.25
  cols_2_drop:
    - PassengerId
  cat_var:
    - Pclass
    - Name
    - Sex
    - Ticket
    - Cabin
    - Embarked
    - Ticket_1p
    - Cabin_1p
    - Embarked_mod
    - SibSp_mod
  num_var:
    - Age
    - SibSp
    - Parch
    - Fare
  target: 
    - Survived
model_selection:
  score: 'roc_auc'